services:
  - type: web
    name: toolsmith
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install psycopg2-binary --no-cache-dir
    startCommand: |
      python -c "from app import app, db; app.app_context().push(); db.create_all()" && \
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: toolsmith-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FLUX_API_KEY
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains

databases:
  - name: toolsmith-db
    databaseName: toolsmith
    plan: free
    ipAllowList: [] # only allow internal connections 